title: MIAAIM
description: Multi-modal image alignment and analysis by information manifolds

remote_theme: CloudCannon/edition-jekyll-template


plugins:
  - jekyll-seo-tag
  - jekyll-remote-theme


repository: JoshuaHess12/miaaim

theme: jekyll-theme-slate